config/routes.rb
Rails.application.routes.draw do
  
  resources :ajax_tests
  
  resources :competencies do
    member do
      get :delete
    end
  end
  resources :partners do
     member do
       get :delete
       get :add_memberships
       get :delete_memberships
     end
  end
  resources :partner_memberships do
    member do
      get :delete
    end
  end
  resources :competency_levels do
    member do
      get :delete
    end
  end
  resources :partner_levels do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partner_membership.rb
class PartnerMembership < ApplicationRecord
  belongs_to :partner
  belongs_to :competency
  belongs_to :competency_level
  
  
end

app/controllers/partner_memberships_controller.rb
class PartnerMembershipsController < ApplicationController
  before_action :check_for_cancel, only: [:create, :update, :destroy]
  respond_to :html, :js
 
  def index
    @partner_memberships = PartnerMembership.all
  end
  def new
    if @partner.nil?
      @partner_membership = PartnerMembership.new
      
    else
      @current_memberships = @partner.competencies.all
      if @current_memberships.size == 0
        @available_memberships = Competency.sorted
      else
        curr_membership_array = @current_memberships.map{ |comp_id| comp_id.id }
        @available_memberships = Competency.where.not(id: curr_membership_array)
      end
      @partner_membership = @partner.partner_memberships.build
    end
  end
  
  def create
    @partner = Partner.find(params[:partner_membership][:partner_id])
    @partner_membership = @partner.partner_memberships.build(allowed_params)
    respond_to do |format|
      if @partner_membership.save
        format.html { redirect_to(partner_path(@partner_membership.partner_id)) }
        format.js { render action: 'partners/show', status: :created, location: @partner_membership }
      end 
    end
    
  end
  
  def show
    
  end
  
  def edit
    @partner_membership = PartnerMembership.find(params[:id])
  end
  
  def update
    @partner_membership = PartnerMembership.find(params[:id])
    if @partner_membership.update_attributes(allowed_params) 
        flash[:notice] = "Partner Competency Membership was successfully updated"
        redirect_to(partner_path(@partner_membership.partner_id))
    else
        render('edit')
    end  
  end
  
  def delete
    @partner_membership = PartnerMembership.find(params[:id])
  end
  
  def destroy
    @partner_membership = PartnerMembership.find(params[:id])
    @partner = @partner_membership.partner
    @partner_membership.destroy
    flash[:notice] = "Partner membership '#{@partner_membership.competency.name}' was successfully deleted for '#{@partner_membership.partner.name}'"
    
    respond_to do |format|
      format.html { redirect_to(partner_path(@partner_membership.partner_id)) }
      format.js { render 'partners/show', status: :created, location: @partner}
    end 
  end
  

  
  private
  
  def allowed_params
    params.require(:partner_membership).permit(:partner_id, :competency_id, :num_vse, :num_vseplus, :num_vcs, :competency_level_id)
    
  end
  
  def check_for_cancel
    puts "I made it here"
    if params[:commit] == "Cancel"
      @partner_membership = PartnerMembership.find(params[:id])
      redirect_to(partner_path(@partner_membership.partner_id))
    end
  end

end

app/helpers/partner_memberships_helper.rb
module PartnerMembershipsHelper
end

app/views/partner_memberships/_form.html.erb
<%= error_messages_for(f.object) %>

	<table>
		<tr>
			<th>Competency Level: </th>
			<td><%= f.collection_select(:competency_level_id, CompetencyLevel.all, :id, :name) %></td>
		</tr>
		<tr>
			<th>Number of VSE</th>
			<td><%= f.number_field(:num_vse, size: 2)  %></td>
		</tr>
		<tr>
			<th>Number of VSEplus</th>
			<td><%= f.number_field(:num_vseplus, size: 2)  %></td>
		</tr>
		<tr>
			<th>Number of VCS</th>
			<td><%= f.number_field(:num_vcs, size: 2)  %></td>
		</tr>		
	</table>
	

app/views/partner_memberships/_new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel">Add Partner Membership</h3>
</div>


	<% if @partner.nil? %>
		<div class="modal-body">
		<%= form_for(@partner_membership, :remote => true) do |pm| %>
			<table class="table">
				<tr><td>Partner: </td><td><%= pm.collection_select(:partner_id, Partner.sorted, :id, :name) %></td></tr>
				<tr><td>Competency: </td><td><%= pm.collection_select(:competency_id, Competency.sorted, :id, :name) %></td></tr>
				<tr><td>Competency Level: </td><td><%= pm.collection_select(:competency_level_id, CompetencyLevel.all, :id, :name)%></td></tr>
				<tr><td>Number of VSE: </td><td><%= pm.number_field(:num_vse) %></td></tr>
				<tr><td>Number of VSEplus: </td><td><%= pm.number_field(:num_vseplus) %></td></tr>
				<tr><td>Number of VCS: </td><td><%= pm.number_field(:num_vcs) %></td></tr>
			</table>

			<%= pm.submit("Save") %>			
		</div>
		<% end %>
	<% else %>
		<div class="modal-body">
		<%= form_for(partner_membership, :remote => true) do |pm| %>
			<table class="table">
				<tr><td>Competency: </td><td><%= pm.collection_select(:competency_id, @available_memberships, :id, :name) %></td></tr>
				<tr><td>Competency Level: </td><td><%= pm.collection_select(:competency_level_id, CompetencyLevel.all, :id, :name)%></td></tr>
				<tr><td>Number of VSE: </td><td><%= pm.number_field(:num_vse) %></td></tr>
				<tr><td>Number of VSEplus: </td><td><%= pm.number_field(:num_vseplus) %></td></tr>
				<tr><td>Number of VCS: </td><td><%= pm.number_field(:num_vcs) %></td></tr>
			</table>
			<%= pm.hidden_field(:partner_id) %>
			<%= pm.submit("Save") %>
		</div>
		

		<% end %>
	<% end %>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>

app/views/partner_memberships/_partner_membership_table_row.html.erb
			<tr>
				<td><%= link_to('', edit_partner_membership_path(membership.id), {data: {toggle: "tooltip"}, title: 'edit', class: "glyphicon glyphicon-edit"}) %><%= link_to('', delete_partner_membership_path(membership.id), {data: {toggle: "tooltip"}, title: 'delete', class: "glyphicon glyphicon-remove"})%></td>
				<td><%= membership.partner.name %></td>
				<td data-toggle="tooltip" title="<%= membership.competency.description %>"><%= membership.competency.name %></td>
				<td>
					<% if !membership.competency_level.nil? %>
						<%= membership.competency_level.name %>
					<% else %>
						Competency Level required
					<% end %>
					
				</td>
				<td><%= membership.num_vse %></td>
				<td><%= membership.num_vseplus %></td>
				<td><%= membership.num_vcs %></td>
			</tr>

app/views/partner_memberships/create.html.erb
<h1>Values for Create</h1>

<table class="table">
	<thead>
		<th>Partner ID</th>
		<th>Competency ID</th>
	</thead>
	<tbody>
		<tr>
				<td><%= @partner_id.id %></td>
				<td><%= @competency %></td>
		</tr>
	</tbody>
</table>

app/views/partner_memberships/create.js.erb
var markup = "<tr><td><%= link_to('', edit_partner_membership_path(@partner_membership.id), {data: {toggle: "tooltip"}, title: 'edit', class: "glyphicon glyphicon-edit"}) %><%= link_to('', delete_partner_membership_path(@partner_membership.id), {data: {toggle: "tooltip"}, title: 'delete', class: "glyphicon glyphicon-remove"})%></td>";
markup += "<td data-toggle="tooltip" title="<%= @partner_membership.competency.description %>"><%= @partner_membership.competency.name %></td>";
markup += "<td><%= @partner_membership.competency_level.name %></td>";
markup += "<td><%= @partner_membership.num_vse %></td>";
markup += "<td><%= @partner_membership.num_vseplus %></td>";
markup += "<td><%= @partner_membership.num_vcs %></td>";
markup += "</tr>";
$(#competencies tbody).append(markup);
$("#myModal").modal('hide');

app/views/partner_memberships/delete.html.erb
<% @page_title = "Delete Competency #{@partner_membership.competency.name} for Partner #{@partner_membership.partner.name}" %>
<h1>Competency delete for Partner</h1>



<%= form_for(@partner_membership, :method => 'delete') do |f| %>
	<p>You are about to delete the competency <em><%= f.object.competency.name %></em> for partner: <em><%= f.object.partner.name %></em></p>
	<%= f.submit("Delete") %>
	<%= f.submit("Cancel") %>
<% end %>
<br />
<%= link_to("Home", partners_path)%>

app/views/partner_memberships/edit.html.erb
<h1>Edit Competency membership for <%= @partner_membership.partner.name %></h1>

<%= form_for(@partner_membership) do |f| %>
	<%= render(:partial => 'form', :locals => {:f => f}) %>
	
	<%= f.submit("Save") %>
<% end %>
<br />

<%= link_to("Home", {:action => 'index'})%>

app/views/partner_memberships/index.html.erb
<h1>Partner membership index</h1>

<table class="table">
	<thead>
		<td></td>
		<td>Partner</td>
		<td>Competency</td>
		<td>Competency Level</td>
		<td># of VSE</td>
		<td># of VSEplus</td>
		<td># of VCS</td>
	</thead>
	<tbody id="PartnerMembershipTableBody">
	<% @partner_memberships.each do |pm| %>
		<%= render partial: 'partner_membership_table_row', locals: { membership: pm } %>
	<% end %>
	</tbody>
</table>

<%= link_to('',new_partner_membership_path, {:remote => true, class: 'glyphicon glyphicon-plus', 'data-toggle' => "modal", 'data-target' => "#myModal", 'type' => "button"})%>

<div id="myModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content"></div>
	</div>
</div>

app/views/partner_memberships/new.html.erb
<h1>New Partner Membership</h1>

<%= form_for(@partner_membership) do |pm| %>
	<%= pm.collection_select(:partner_id, Partner.sorted, :id, :name)%>
	<%=	pm.collection_select(:competency_id, Competency.sorted, :id, :name) %>
	<%= pm.collection_select(:competency_level_id, CompetencyLevel.all, :id, :name)%>
	<%= pm.number_field(:num_vse) %>
	<%= pm.number_field(:num_vseplus) %>
	<%= pm.number_field(:num_vcs) %>
	<%= pm.submit('Save')%>
<% end %>
	

app/views/partner_memberships/new.js.erb
$("#myModal").find(".modal-content").html("<%= j (render 'new') %>");

app/views/partner_memberships/show.js.erb
$('#PartnerMembershipTableBody').append(<%= j render partial: 'partner_membership_table_row', locals: { membership: @partner_membership }%>);
$("#myModal").modal('hide');