config/routes.rb
Rails.application.routes.draw do
  
  resources :ajax_tests
  
  resources :competencies do
    member do
      get :delete
    end
  end
  resources :partners do
     member do
       get :delete
       get :add_memberships
       get :delete_memberships
     end
  end
  resources :partner_memberships do
    member do
      get :delete
    end
  end
  resources :competency_levels do
    member do
      get :delete
    end
  end
  resources :partner_levels do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :partner_memberships
  has_many :competencies, :through => :partner_memberships
  belongs_to :partner_level
  
  scope :sorted, -> { order("name ASC") }
  
  validates_presence_of :name
  
  
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  #layout false
  
  def index
    @partners = Partner.sorted
  end

  def show
    @partner = Partner.find(params["id"])
  end

  def edit
    @partner = Partner.find(params["id"])
    @partner_levels = PartnerLevel.all
    
  end
  
  def new
    @partner = Partner.new
    @all_competencies = Competency.sorted
    @partner_memberships = @partner.partner_memberships.build
    @partner_levels = PartnerLevel.all
    
  end
  
  def create
    @partner = Partner.new(allowed_params)
    
    params[:competencies][:id].each do |comps|
      if !comps.empty?
        @partner.partner_memberships.build(:competency_id => comps)
      end
    end
    
    if @partner.save
      flash[:notice] = "Partner was successfully added"
      redirect_to(partners_path)
    else
      render('new')
    end
  end
  
  def update
    flash[:notice] = ''
    @partner = Partner.find(params[:id])
    edit_type = params[:edit_type]
    if edit_type == "Edit Partner"
      if @partner.update_attributes(allowed_params) 
        flash[:notice] = "Partner was successfully updated && Edit Type was #{edit_type}"
        redirect_to(partner_path(@partner))
      else
        render('edit')
      end  
    elsif edit_type == "Add Partner"
      @partner_membership = @partner.partner_memberships.build(allowed_partern_membership_params)
      if @partner.save
        respond_to do |format|
          format.html { redirect_to(partner_path(@partner)) }
          format.js { render action: 'show', status: :created, location: @partner_membership } 
        end
      end
    end
  end

  def delete
    @partner = Partner.find(params["id"])
  end
  
  def destroy
    @partner = Partner.find(params["id"])
    @partner.destroy
    flash[:notice] = "Partner '#{@partner.name}'was successfully deleted"
    redirect_to(partners_path)    
  end
  
  def add_memberships
    @partner = Partner.find(params['id'])
    @curr_memberships = PartnerMembership.where(partner_id: @partner.id)
    @new_memberships = @partner.partner_memberships.build
    if @curr_memberships.size == 0
      @available_memberships = Competency.sorted
    else
      curr_membership_array = @curr_memberships.map{ |comp_id| comp_id.competency_id }
      @available_memberships = Competency.where.not(id: curr_membership_array)
    end
    
    respond_to do |format|
      format.html
      format.js 
    end
  end
  
  private 
  def allowed_params
    params.require(:partner).permit(:id, :name, :pnet_acct, :partner_membership, partner_membership: [:competency_id, :competency_level_id, :num_vse, :num_vseplus, :num_vcs])
  end
  
  def allowed_partern_membership_params
    params.require(:partner_membership).permit(:competency_id, :competency_level_id, :num_vse, :num_vseplus, :num_vcs)
  end
  
  
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_add_partner_membership.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel">Add Partner Membership</h3>
</div>


<div class="modal-body">
<%= form_for(@partner, :remote => true) do |p| %>
	<%= hidden_field_tag('edit_type', "Add Partner")%>
	<%= p.hidden_field(:id) %>
	<%= fields_for(new_membership) do |pm|%>
	<table class="table">
		<tr><td>Competency: </td><td><%= pm.collection_select(:competency_id, @available_memberships, :id, :name) %></td></tr>
		<tr><td>Competency Level: </td><td><%= pm.collection_select(:competency_level_id, CompetencyLevel.all, :id, :name)%></td></tr>
		<tr><td>Number of VSE: </td><td><%= pm.number_field(:num_vse) %></td></tr>
		<tr><td>Number of VSEplus: </td><td><%= pm.number_field(:num_vseplus) %></td></tr>
		<tr><td>Number of VCS: </td><td><%= pm.number_field(:num_vcs) %></td></tr>
	</table>
	<% end %>
	<%= p.submit('Save')%>
<% end %>		
</div>
		
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>

app/views/partners/_form.html.erb
<%= error_messages_for(f.object) %>

	<table>
		<tr>
			<th>Name: </th>
			<td><%= f.text_field(:name) %></td>
		</tr>
		<tr>
			<th>PartnerNet Account</th>
			<td><%= f.text_field(:pnet_acct)  %></td>
		</tr>
		<tr>
			<th>Status: </th>
			<td><%= f.collection_select(:partner_level_id, @partner_levels, :id, :name) %></td>
		</tr>
	</table>
	

app/views/partners/_partner_membership_table_row.html.erb
			<tr>
				<td><%= link_to('', edit_partner_membership_path(membership.id), {data: {toggle: "tooltip"}, title: 'edit', class: "glyphicon glyphicon-edit"}) %></td>
				<td><%= link_to('', '/partner_memberships/'+membership.id.to_s, method: :delete, remote: true, data: {toggle: "tooltip", confirm: "Are you sure?"}, title: 'delete', class: "glyphicon glyphicon-remove")%></td>
				<td data-toggle="tooltip" title="<%= membership.competency.description %>"><%= membership.competency.name %></td>
				<td>
					<% if !membership.competency_level.nil? %>
						<%= membership.competency_level.name %>
					<% else %>
						Competency Level required
					<% end %>
					
				</td>
				<td><%= membership.num_vse %></td>
				<td><%= membership.num_vseplus %></td>
				<td><%= membership.num_vcs %></td>
			</tr>

app/views/partners/add_memberships.html.erb
<h1>Add Partner Competency Membership</h1>

<h2><%= "#{@partner.name} "%></h2>
<div class="row">
	<div class="col-md-6">
		<p>Current Memberships <span class="badge"><%= @curr_memberships.size %></span></p>
		<% if @curr_memberships.size == 0 %>
			<p>No Current memberships</p>
		<% else %>
			<table class="table">
				<thead>
					<th>Competency Name</th>
					<th>Competency Description</th>
				</thead>
				<tbody>
					<% @curr_memberships.each do |membership| %>
					<tr>
						<td><%= membership.competency.name %></td>
						<td><%= membership.competency.description %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
	<div class="col-md-6">
		<p>Available Memberships <span class="badge"><%= @available_memberships.size %></span></p>
		<% if @available_memberships.size == 0 %>
			<p>No available competencies to add</p>
		<% else %>
			<table class="table">
				<thead>
					<th>Competency Name</th>
					<th>Competency Description</th>
				</thead>
				<tbody>
					<% @available_memberships.each do |competency| %>
					<tr>
						<td><%= competency.name %></td>
						<td><%= competency.description %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
</div>
<div class="row">
	<%= form_for(@partner) do |p| %>
		<%= p.hidden_field(:edit_type, :value=>"Add Partner")%>
		<%= fields_for(@new_memberships) do |f| %>
			<%= f.label "Select Competencies to Add" %><br />
			<%=	collection_select(:competencies, :id, @available_memberships, :id, :name, {}, { multiple: true }) %>
			<br />
			<%= f.submit("Save") %>
		<% end %>
	<% end %>
</div>

app/views/partners/add_memberships.js.erb
$("#myModal").find(".modal-content").html("<%= j (render :partial => 'add_partner_membership', :locals => {:new_membership => @partner.partner_memberships.build } ) %>");

app/views/partners/delete.html.erb
<% @page_title = "Delete Partner #{@partner.name}" %>
<h1>Partner delete</h1>



<%= form_for(@partner, :method => 'delete') do |f| %>
	<p>You are about to delete a partner: <%= f.object.name %></p>
	<%= f.submit("Delete Partner") %>
<% end %>
<br />
<%= link_to("Home", {:action => 'index'})%>

app/views/partners/edit.html.erb
<% @page_title = "Edit #{@partner.name}" %>

<h1>Partner edit</h1>

<%= form_for(@partner) do |f| %>

	<%= render(:partial => 'form', :locals => {:f => f}) %>
	<%= hidden_field(:edit_type => "Edit Partner")%>
	<%= f.submit("Save") %>
<% end %>
<br />

<%= link_to("Home", {:action => 'index'})%>

app/views/partners/index.html.erb
<% @page_title = "All Partners" %>
<h1>Partners</h1>
<div class="row">
	<div class="col-md-6">
		<table class="table">
			<thead>
				<th></th>
				<th>Partner</th>
				<th>Level</th>
			</thead>
			<tbody>
			<% @partners.each do |partner| %>
				<tr>
					<td><%= link_to('', edit_partner_path(partner), {data: {toggle: "tooltip"}, title: 'edit', class: "glyphicon glyphicon-edit"}) %><%= link_to('', delete_partner_path(partner), {data: {toggle: "tooltip"}, title: 'delete', class: "glyphicon glyphicon-remove"})%></td>
					<td><%= link_to(partner["name"], partner_path(partner)) %></td>
					<td><%= partner.partner_level.name %></td>
				</tr>
			<% end %>
		<br />
			</tbody>
		</table>
	</div>
</div>
<div class="row"><p><%= link_to('New', new_partner_path)%></p></div>

app/views/partners/new.html.erb
<% @page_title = "New Partner" %>
<h1>New Partner</h1>

<%= form_for(@partner) do |f| %>
	
	<%= render(:partial => 'form', :locals => {:f => f}) %>
	<hr />
	<%= fields_for(@partner_memberships) do |pm| %>
		<%= pm.label "All Competencies" %><br />
		<%= collection_select(:competencies, :id, @all_competencies, :id, :name, {}, { multiple: true }) %>
	<% end %>
	<br />
	<%= f.submit("Create Partner") %>
<% end %>

<br />

<%= link_to("Home", partners_path)%>

app/views/partners/show.html.erb
<% @page_title = "Details for #{@partner.name}" %>

<h1><%= "#{@partner.name}" %></h1>

<table>
	<tbody>
		<tr>
			<td>PartnerNet Account:</td>
			<td><%= @partner.pnet_acct %></td>
		</tr>
		<tr>
			<td>Status:</td>
			<td><%= @partner.partner_level.name %></td>
		</tr>
		<tr>
			<td>Created at :</td>
			<td><%= @partner.created_at.strftime('%d-%b-%Y %T') %></td>
		</tr>
		<tr>
			<td>Updated at :</td>
			<td><%= @partner.updated_at.strftime('%d-%b-%Y %T') %></td>
		</tr>
		<tr>
			<td>Number of Competencies: </td>
			<td><span class="badge" id="numCompetencies"><%= @partner.competencies.size %></span>
				<button class="btn btn-xs showTableBtn" data-target="#competencies">Show</button>
				<button class="btn btn-xs hideTableBtn" data-target="#competencies">Hide</button>
			</td>
		</tr>
	</tbody>
</table>
<br />
<table id="competencies" class="table">
	<thead>
		<th></th>
		<th></th>
		<th>Competency Name</th>
		<th>Competency Level</th>
		<th>Number of VSE</th>
		<th>Number of VSEplus</th>
		<th>Number of VCS</th>
	</thead>
	<tbody id="PartnerMembershipTableBody">
		<% @partner.partner_memberships.each do |membership| %>
			<%= render partial: 'partner_membership_table_row', locals: {membership: membership} %>
		<% end %>
	</tbody>
</table>
<% if @partner.competencies.size < Competency.all.size %>
					<%= link_to('',add_memberships_partner_path(@partner), {:remote => true, class: 'glyphicon glyphicon-plus', 'data-toggle' => "modal", 'data-target' => "#myModal", 'type' => "button"})%>
				<% end %>
<div id="myModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content"></div>
	</div>
</div>
<br />
<%= link_to('<button>Edit</button>'.html_safe, edit_partner_path) %>
<%= link_to('<button>Delete</button>'.html_safe, delete_partner_path) %>
<br /><br />
<%= link_to("Home", partners_path)%>

app/views/partners/show.js.erb
$("#PartnerMembershipTableBody").html("<% @partner.partner_memberships.each do |membership| %><%= j render partial: 'partner_membership_table_row', locals: {membership: membership} %><% end %>");
$("#numCompetencies").html("<%= @partner.competencies.size %>");
$("#myModal").modal('hide');

app/views/partners/update.js.erb
$('#PartnerMembershipTableBody').append(<%= j render partial: 'partner_membership_table_row', locals: { membership: @partner_membership }%>);
$("#myModal").modal('hide');