config/routes.rb
Rails.application.routes.draw do
  
  resources :ajax_tests
  
  resources :competencies do
    member do
      get :delete
    end
  end
  resources :partners do
     member do
       get :delete
       get :add_memberships
       get :delete_memberships
     end
  end
  resources :partner_memberships do
    member do
      get :delete
    end
  end
  resources :competency_levels do
    member do
      get :delete
    end
  end
  resources :partner_levels do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/competency.rb
class Competency < ApplicationRecord
  has_many :partner_memberships
  has_many :partners, :through => :partner_memberships
  belongs_to :competency_type
  
  scope :sorted, -> { order("name ASC") }
end

app/models/competency_type.rb
class CompetencyType < ApplicationRecord
  has_many :competencies
end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  def index
    @competencies = Competency.sorted
  end

  def show
    @competency = Competency.find(params["id"])
  end
  
  def new
    @competency = Competency.new
  end
  
  def create
    @competency = Competency.new(allowed_params)
    if @competency.save
      flash[:notice] = "Competency was successfully added"
      redirect_to(competencies_path)
    else
      flash[:notice] = "Competency was not successfully updated"
      render('new')
    end
  end

  def edit
    @competency = Competency.find(params["id"])
  end
  
  def update
     @competency = Competency.find(params["id"])
    
    if @competency.update_attributes(allowed_params)
      flash[:notice] = "Competency was successfully updated"
      redirect_to(competency_path(@competency))
    else
      flash[:notice] = "Competency was not successfully updated"
      render('edit')
    end  
  end

  def delete
  end
  
  def destroy
    
  end
  
  private
  def allowed_params
    params.require(:competency).permit(:name, :description, :competency_type_id)
  end
end

app/helpers/competencies_helper.rb
module CompetenciesHelper
end

app/views/competencies/_form.html.erb
<%= error_messages_for(f.object) %>

	<table>
		<tr>
			<th>Name: </th>
			<td><%= f.text_field(:name) %></td>
		</tr>
		<tr>
			<th>Description: </th>
			<td><%= f.text_area(:description) %></td>
		</tr>
		<tr>
			<th>Type: </th>
			<td><%= f.collection_select(:competency_type_id, CompetencyType.all, :id, :name) %></td>
		</tr>
	</table>
	

app/views/competencies/delete.html.erb
<h1>Competencies#delete</h1>
<p>Find me in app/views/competencies/delete.html.erb</p>

app/views/competencies/edit.html.erb
<% @page_title = "Edit #{@competency.name}" %>

<h1>Competency edit</h1>

<%= form_for(@competency) do |f| %>

	<%= render(:partial => 'form', :locals => {:f => f}) %>

	<%= f.submit("Update Competency") %>
<% end %>
<br />

<%= link_to("Home", competencies_path)%>

app/views/competencies/index.html.erb
<% @page_title = "All Competencies" %>
<h1>Competencies</h1>

<div class="row">
	<div class="col-md-6">
		<table class="table">
			<thead>
				<th></th>
				<th>Competency</th>
				<th>Competency Type</th>
			</thead>
			<tbody>
			<% @competencies.each do |competency| %>
				<tr>
					<td><%= link_to('', edit_competency_path(competency), {data: {toggle: "tooltip"}, title: 'edit', class: "glyphicon glyphicon-edit"}) %><%= link_to('', delete_competency_path(competency), {data: {toggle: "tooltip"}, title: 'delete', class: "glyphicon glyphicon-remove"})%></td>
					<td><%=link_to(competency["name"], competency_path(competency)) %></td>
					<td><%= competency.competency_type.name %></td>
				</tr>
			<% end %>
		<br />
			</tbody>
		</table>
	</div>
</div>
<div class="row"><%= link_to('New', new_competency_path)%></div>

app/views/competencies/new.html.erb
<% @page_title = "New Competency" %>
<h1>New Competency</h1>

<%= form_for(@competency) do |f| %>
	
	<%= render(:partial => 'form', :locals => {:f => f}) %>
	
	<%= f.submit("Create Competency") %>
<% end %>

<br />

<%= link_to("Home", competencies_path)%>

app/views/competencies/show.html.erb
<% @page_title = "Details for #{@competency.name}" %>

<h1><%= "#{@competency.name} "%></h1>

<table>
	<tr>
		<td>Description:</td>
		<td><%= @competency.description %></td>
	</tr>
	<tr>
		<td>Type:</td>
		<td><%= @competency.competency_type.name %></td>
	</tr>
	<tr>
		<td>Created at :</td>
		<td><%= @competency.created_at.strftime('%d-%b-%Y %T') %></td>
	</tr>
	<tr>
		<td>Updated at :</td>
		<td><%= @competency.updated_at.strftime('%d-%b-%Y %T') %></td>
	</tr>
	<tr>
		<td>Number of Partners: </td>
		<td><%= @competency.partners.size %> <button class="showTableBtn" data-target="#partners">Show</button><button class="hideTableBtn" data-target="#partners">Hide</button></td>
	</tr>
	<tr>
		<table id="partners">
			<thead>
				<th>Partner Name <%= link_to('Add Partner')%></th>
			</thead>
			<tbody>
				<% @competency.partners.each do |partner| %>
					<tr>
						<td><%= partner.name %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</tr>
</table>
<br />
<%= link_to('<button>Edit</button>'.html_safe, edit_competency_path) %>
<%= link_to('<button>Delete</button>'.html_safe, delete_competency_path) %>
<br /><br />
<%= link_to("Home", competencies_path)%>