config/routes.rb
Rails.application.routes.draw do
  
  resources :ajax_tests
  
  resources :competencies do
    member do
      get :delete
    end
  end
  resources :partners do
     member do
       get :delete
       get :add_memberships
       get :delete_memberships
     end
  end
  resources :partner_memberships do
    member do
      get :delete
    end
  end
  resources :competency_levels do
    member do
      get :delete
    end
  end
  resources :partner_levels do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ajax_test.rb
class AjaxTest < ApplicationRecord
end

app/controllers/ajax_tests_controller.rb
class AjaxTestsController < ApplicationController
  before_action :set_ajax_test, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /ajax_tests
  # GET /ajax_tests.json
  def index
    @ajax_tests = AjaxTest.all
    @new_ajax_test = AjaxTest.new
  end

  # GET /ajax_tests/1
  # GET /ajax_tests/1.json
  def show
  end

  # GET /ajax_tests/new
  def new
    @new_ajax_test = AjaxTest.new
  end

  # GET /ajax_tests/1/edit
  def edit
  end

  # POST /ajax_tests
  # POST /ajax_tests.json
  def create
    @ajax_test = AjaxTest.new(ajax_test_params)

    respond_to do |format|
      if @ajax_test.save
        format.html { redirect_to @ajax_test, notice: 'Ajax test was successfully created.' }
        format.json { render :show, status: :created, location: @ajax_test }
        format.js { render action: 'show', status: :created, location: @ajax_test }
      else
        format.html { render :new }
        format.json { render json: @ajax_test.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /ajax_tests/1
  # PATCH/PUT /ajax_tests/1.json
  def update
    respond_to do |format|
      if @ajax_test.update(ajax_test_params)
        format.html { redirect_to @ajax_test, notice: 'Ajax test was successfully updated.' }
        format.json { render :show, status: :ok, location: @ajax_test }
      else
        format.html { render :edit }
        format.json { render json: @ajax_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ajax_tests/1
  # DELETE /ajax_tests/1.json
  def destroy
    @ajax_test.destroy
    respond_to do |format|
      format.html { redirect_to ajax_tests_url, notice: 'Ajax test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ajax_test
      @ajax_test = AjaxTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ajax_test_params
      params.require(:ajax_test).permit(:name)
    end
end

app/helpers/ajax_tests_helper.rb
module AjaxTestsHelper
end

app/views/ajax_tests/_form.html.erb
<%= form_for(@new_ajax_test, :remote => true) do |f| %>
  <% if @new_ajax_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ajax_test.errors.count, "error") %> prohibited this ajax_test from being saved:</h2>

      <ul>
      <% ajax_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="table">
  	<tr>
  		<td>Name: </td>
  		<td><%= f.text_field(:name)%></td>
  	</tr>
  </table>

<%= f.submit('Save') %>
<!--  <div class="actions"> 
    <%= f.submit('Save') %>
  </div>
-->
<% end %>

app/views/ajax_tests/_new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel">Add Ajax Test</h3>
</div>

<div class="modal-body">
	<%= render 'form' %>
</div>

<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    
</div>

app/views/ajax_tests/_table_row.html.erb
      <tr>
      	<td><%= ajax_test.name %></td>
        <td><%= link_to 'Show', ajax_test %></td>
        <td><%= link_to 'Edit', edit_ajax_test_path(ajax_test) %></td>
        <td><%= link_to 'Destroy', ajax_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/ajax_tests/create.js.erb
$("#myModal").find(".modal-content").html();

app/views/ajax_tests/edit.html.erb
<h1>Editing Ajax Test</h1>

<%= render 'form', ajax_test: @ajax_test %>

<%= link_to 'Show', @ajax_test %> |
<%= link_to 'Back', ajax_tests_path %>

app/views/ajax_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ajax Tests</h1>

<table id="TestTable" class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="TestTableBody">
    <% @ajax_tests.each do |ajax_test| %>
		<%= render partial: "table_row", locals: { ajax_test: ajax_test } %>
    <% end %>
  </tbody>
</table>


<div id="task-form" style="display: none;"></div>



<br>

<%= link_to '', '#', {:remote => true, class: 'glyphicon glyphicon-plus', 'data-toggle' => "modal", 'data-target' => "#myModal", 'type' => "button"}  %>
<br />
<%= link_to('',new_ajax_test_path, {:remote => true, class: 'glyphicon glyphicon-plus', 'data-toggle' => "modal", 'data-target' => "#myModal", 'type' => "button"})%>


<div id="myModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h3 id="myModalLabel">Add Ajax Test</h3>
			</div>
			
			<div class="modal-body">
				<%= render 'form' %>
			</div>

			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>    
			</div>			
		</div>
	</div>
</div>

app/views/ajax_tests/new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel">Add Ajax Test</h3>
</div>

<div class="modal-body">
  <table class="table">
  	<%= form_for(@ajax_test, :remote => true) do |f| %>
  	<tr>
  		<td>Name: </td>
  		<td><%= f.text_field(:name)%></td>
  	</tr>
  	<%= f.submit('Save') %>
  	<% end %>
  </table>
</div>

<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    
</div>	

app/views/ajax_tests/new.js.erb
//$('#task-form').html("<%= j (render 'form') %>");
//$('#task-form').slideDown(350);

//$("#myModal").find(".modal-content").html("<%= j (render :partial => 'new', :locals => { :ajax_test => @ajax_test } ) %>");
$("#myModal").find(".modal-content").html("<%= j (render 'new') %>");

app/views/ajax_tests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ajax_test_path(@ajax_test) %> |
<%= link_to 'Back', ajax_tests_path %>

app/views/ajax_tests/show.js.erb
$('#TestTableBody').append("<%= j render partial: "table_row", locals: { ajax_test: @ajax_test }%>");
$('#myModal').modal('hide');